### ISSUE TITLE
Custom Refresh Interval for Each Tile

### ISSUE THREAD

**Issue by ManojKiranA** [fidum/laravel-dashboard-chart-tile#1]
is it possible to make seperate refresh interval for each tile

**Comment by dmason30** [comment]
Good idea. Feel free to send in a PR with this change.

**Comment by dmason30** [comment]
@ManojKiranA Released in 1.1.0

**Comment by ManojKiranA** [comment]
thanks a lot @dmason30

**Comment by ManojKiranA** [comment]
Please update the readme file so that new users may find it helpful

**Comment by dmason30** [comment]
@ManojKiranA Already added here https://github.com/fidum/laravel-dashboard-chart-tile/blob/master/README.md#optional-properties
