### ISSUE TITLE
Failure in loading chartisan from Unpkg

### ISSUE THREAD

**Issue by r-pennings** [fidum/laravel-dashboard-chart-tile#10]
Yesterday, there was an update in the `chartisan` script, resulting in a 2.1.0 version [(see npmjs.com)](https://www.npmjs.com/package/@chartisan/chartjs).

In your package, you are using the path `https://unpkg.com/@chartisan/chartjs@^2.0/dist/chartisan_chartjs.js`. This path will always use the latest V2. The result is as follows:
![image](https://user-images.githubusercontent.com/27762458/87765361-fba63c00-c817-11ea-8460-8569e60ad4ef.png)

When I add a tagged version (for example: `https://unpkg.com/@chartisan/chartjs@2.0.3/dist/chartisan_chartjs.js`) to the dashboard-config file (`dashboard.tiles.charts.scripts`) the script still works.

**Comment by dmason30** [comment]
Sorry, I assumed that they were following semver and there wouldn't be any breaking changes in minor releases. I will switch to a fixed version by default for now.

**Comment by dmason30** [comment]
@r-pennings Released to use fixed versions in v3.1.0 🚀

**Comment by ConsoleTVs** [comment]
We now have to use https://unpkg.com/@chartisan/chartjs@2.1.0/dist/chartisan_chartjs.umd.js

UMD bundle does now include the logic to work under CDN import.

**Comment by dmason30** [comment]
v3.1.1 released using the new UMD build 🎉
