### ISSUE TITLE
Add support for v2 of laravel-dashboard

### ISSUE THREAD

**Issue by freekmurze** [fidum/laravel-dashboard-chart-tile#14]
Hi, 

we've released v2 our dashboard. The only change are the updated requirements: we now require Laravel v8 and Livewire v2.

Could you please tag a new release of your tile?

In most cases these are the things you need to do:
- update the requirement in the composer.json of your tile to "spatie/laravel-dashboard": "^2.0"
- tag a new release. Personally, I would opt for a major release, so you can still do bug fixes on the v1 of your tile.

Thanks!

**Comment by dmason30** [comment]
Just waiting for https://github.com/ConsoleTVs/Charts to release an L8 compatible version and we should be good to go. 🚀
