### ISSUE TITLE
area chart example

### ISSUE THREAD

**Issue by s4muel** [fidum/laravel-dashboard-chart-tile#16]
could you please add an example for area chart?
i am using chart.js (out of the box), that should support area charts by setting filling mode (https://www.chartjs.org/docs/latest/charts/area.html#filling-modes)... but i am struggling with setting that.

**Comment by dmason30** [comment]
Sorry, this package is just a wrapper around https://github.com/ConsoleTVs/Charts please ask configuration questions there. After a brief look currently it doesn't support setting options on a per dataset level. However, there maybe a workaround and someone on that package could help.

**Comment by s4muel** [comment]
thanks, mate
