### ISSUE TITLE
How to make a mixed Chart

### ISSUE THREAD

**Issue by ibrahimMahfuz** [fidum/laravel-dashboard-chart-tile#19]
hello, thank you for making this package, its saved my times a lot,
but i don't know how to make a mixed (bar and line) chart,

please somebody explain to me..

**Comment by dmason30** [comment]
Sorry, this package is just a wrapper around https://github.com/ConsoleTVs/Charts please ask configuration questions there. After a brief look currently it doesn't support setting options on a per dataset level. However, there maybe a workaround and someone on that package could help.
