### ISSUE TITLE
consoletvs/charts not available anymore

### ISSUE THREAD

**Issue by arwinvdv** [fidum/laravel-dashboard-chart-tile#23]
First of all, thanks for making this package!

When try to install I get the error
`Failed to download consoletvs/charts from dist`
Looks like https://github.com/ConsoleTVs/Charts doesn't support version 7.2

**Comment by dmason30** [comment]
Can you show the full error please? 

That dependency allows `>= 7.0`:
https://github.com/ConsoleTVs/Charts/blob/main/composer.json#L7

**Comment by dmason30** [comment]
Seems you have found the related issue https://github.com/ConsoleTVs/Charts/issues/1

Closing as it seems the dependency will be sorted soon.

**Comment by dmason30** [comment]
@arwinvdv Tagged 5.0.0 reverting to charts v6
