### ISSUE TITLE
Upgrade to ConsoleTVs/Charts 7

### ISSUE THREAD

**Issue by ssmusoke** [fidum/laravel-dashboard-chart-tile#6]
is it possible to upgrade to the v7 of ConsoleTVs/Charts

**Comment by dmason30** [comment]
Yes, unfortunately since the whole charts package API has changed for v7 it is quite a big change but I will get to it as soon as i can.

**Comment by dmason30** [comment]
Hi @ssmusoke This has been released in version 3.0.0. Chart class api has changed completely so let me know if you have any issues upgrading.

**Comment by ssmusoke** [comment]
Awesome, excellent job thank you
