### ISSUE TITLE
Consider other front-ends

### ISSUE THREAD

**Issue by ConsoleTVs** [fidum/laravel-dashboard-chart-tile#8]
Have you considered echarts as a chart.js alternative? Chartisan supports it out of the box and have much more features. It is also from the apache foundation.

They can be customized to points where chart.js can't even reach. Check out their example pages!

Perhaps this library could allow to switch between both with ease?

Nice work btw!

**Comment by dmason30** [comment]
Hi @ConsoleTVs I have released the ability to configure the scripts used in v3.0.3. Thanks for the suggestion! :tada:

**Comment by ConsoleTVs** [comment]
Great to hear!
